routes:

 /fund/: fund
 /fund/event-grants/: fund-events-grants 
 /fund/aktivisti-grants/: fund-aktivisti-grants  

collections:
  /:
    permalink: /{slug}/
    template:
      - index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
